version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Sentry
    versions:
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
    - 3.3.4
  - dependency-name: Microsoft.AspNetCore.SignalR.Client
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.SignalR.Protocols.MessagePack
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite.Core
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.NETCore.Targets
    versions:
    - 5.0.0
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - 5.0.1
  - dependency-name: Microsoft.Extensions.Configuration.Abstractions
    versions:
    - 5.0.0
  - dependency-name: ppy.osu.Game.Resources
    versions:
    - 2021.211.1
  - dependency-name: Microsoft.CodeAnalysis.BannedApiAnalyzers
    versions:
    - 3.3.2
  - dependency-name: SharpCompress
    versions:
    - 0.28.1
  - dependency-name: ppy.osu.Framework.iOS
    versions:
    - 2021.226.0
  - dependency-name: NUnit
    versions:
    - 3.13.1
  - dependency-name: Dapper
    versions:
    - 2.0.78
  - dependency-name: ppy.osu.Framework.NativeLibs
    versions:
    - 2021.115.0
  - dependency-name: ppy.squirrel.windows
    versions:
    - 1.9.0.5
